### ISSUE TITLE
Feature Request: CSS class parameter

### ISSUE THREAD

**Issue by twiginteractive** [jo-snips/vc-content-block#1]
Hi - first off, great plugin! Bridges the gap between CPW and VC nicely.

One request - could you add a text field in the VC shortcode UI for custom CSS class? The CPW shortcode allows for `[content_block class="classname"]` so by exposing the `class` parameter, we could control that through VC too.

Also - is it possible to display the name of the chosen Content Block in the VC backend-screen once you select one, and click "ADD"? That way when looking at the VC edit screen, you can see which CB was selected in that spot.

Thanks!

**Comment by twiginteractive** [comment]
I know this is old and obviously not monitored by the plugin author, but it was pretty easy to do both the things I mentioned above, so if you have any interest in a version 1.1, just comment and I'll send the code mods or do a Pull request!

**Comment by jonahcoyote** [comment]
Hey @twiginteractive! Sorry for the lack of response, you know how it goes... Yes, please issue a pull request and I'd love to get your changes included :)

**Comment by twiginteractive** [comment]
Hey Jonah!

I've not done much with Git other than managing my own code, so not really sure of the Pull request process - I have Git desktop and a gui for Dreamweaver, but tha'ts about it ☺
The only file I had to touch was shortcodes\content-blocks.php, so let me know the best way to get it to you so you can assess and roll  it in.

Thanks!

Jonathan

---

Jonathan V. Goslin   Principal Developer  Office: 703.237.5706    Mobile: 703.864.2983
Twig Interactive LLC

---

[http://www.twiginteractive.com/graphics/emailsignature/icon_thinkgreen.gif]  Please think before you print.

**Comment by jonahcoyote** [comment]
Hey Jonathan!

No problem. How about just use one of the various online code snippet tools out there? http://www.gistboxapp.com/ looks good and it’s tied into Github or even just plain Gist: https://gist.github.com/ would suffice.

Thanks!
- Jonah

**Comment by twiginteractive** [comment]
Ah nice - that makes it pretty easy to share snips. Hopefully merging it in isn't too painful for you! I really didn’t do that much - just added another option to the array, and set the flag to display in Preview mode.

https://gist.github.com/twiginteractive/2dae78fbe3dc5be86e5a

Thanks Jonah!
JG

**Comment by jonahcoyote** [comment]
Thanks Jonathan! I've actually updated the plugin in another repo here: https://github.com/jonahcoyote/vc-content-block - it contains some other updates and cleaner code for newer versions of VC. I'm going to either delete this repo and/or update this one with that code.
